# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ciência médica e não médica
email: heldercfelix@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog sobre ciência médica, pesquisa científica, oncologia pediátrica,
  farmacologia e outras ciências da saúde afins. Continuação do blog
  publicado em http://pharmakon.blogspot.com
baseurl: /ciencia-medica
url: # the base hostname & protocol for your site
twitter_username: fhcflx
github_username:  fhcflx

# Build settings
markdown: kramdown
subtitle: Ciência médica
author: fhcflx
simple_search: http://google.com/search
name:
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/Fortaleza
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: gh-pages
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination:
