name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ''
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
      - name: Install Gems
        run: |
          echo 'gem "html-proofer"' >> Gemfile
          sed -i 15d _config.yml
          sed -i 1d .gitignore
          bundle install
          chmod +x ./script/cibuild
      - name: Configure Git Author
        run: |
          git config --global user.email "fhcflx@outlook.com"
          git config --global user.name "Francisco Felix"
      - name: Build Jekyll site
        run: ./script/cibuild
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses the standard GitHub token
          BRANCH: gh-pages   # The branch to deploy to
          FOLDER: _site      # The folder containing your built site
          CLEAN: true       # Optional, cleans the destination branch
          REPOSITORY: ${{ github.repository }}