name: Build and Deploy

on:
  push:
    branches:
      - gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build website
        run: |
          echo 'gem "html-proofer"' >> Gemfile
          bundle install
          bundle exec jekyll build

      - name: Run html-proofer
        run: |
          bundle exec htmlproofer ./_site \
            --disable-external \
            --url-ignore "/#/" \
            --alt-ignore '/.*/'

      - name: Update baseurl
        run: echo 'baseurl: "/ciencia-medica"' >> _config.yml

      - name: Build website again
        run: bundle exec jekyll build

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
