name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production # Garante que o ambiente de produção seja usado

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          # with:
          #   repository: ''

        - name: Setup Ruby and Bundler
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 3.1
            bundler-cache: true

      # - name: Install Gems
      #   run: |
      #     echo 'gem "html-proofer"' >> Gemfile
      #     sed -i 15d _config.yml
      #     sed -i 1d .gitignore
      #     bundle install
      #     chmod +x ./script/cibuild
      # - name: Configure Git Author
      #   run: |
      #     git config --global user.email "fhcflx@outlook.com"
      #     git config --global user.name "Francisco Felix"

        - name: Build Jekyll site
          # run: ./script/cibuild
          run: bundle exec jekyll build --destination _site
        
        - name: Test built site with HTMLProofer
          run: |
            bundle exec htmlproofer ./_site \
              --disable-external \
              --ignore-missing-alt \
              --ignore-urls '/^#/' # Ajuste conforme suas necessidades de ignorar URLs
              # Se você precisa ignorar mais URLs, adicione-as como uma lista separada por vírgulas:
              # --ignore-urls '/^#/','/outro/link/problematico/'
              # Se antes o '/.*/' era intencional para ignorar todos os links internos, adicione-o aqui.

        - name: Deploy to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            # TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses the standard GitHub token
            BRANCH: gh-pages   # The branch to deploy to
            FOLDER: _site      # The folder containing your built site
            CLEAN: true       # Optional, cleans the destination branch
            # REPOSITORY-NAME: ${{ github.repository }}